# Script to automate switching compilers for C and C++ files on Windows
# Compilers are gcc.exe and g++.exe
# This script is generated by ChatGPT

param (
    [string]$filePath,
    [string]$buildType = "debug"
)

$ext = [System.IO.Path]::GetExtension($filePath) # Get the extension of the running file .c or .cpp
$outputPath = [System.IO.Path]::ChangeExtension($filePath, '.exe') # During running the file a EXE file appear with the same name

# Choose compiler based on file extension
switch ($ext) {
    ".c"   { $compiler = "C:\msys64\mingw64\bin\gcc.exe" }
    ".cpp" { $compiler = "C:\msys64\mingw64\bin\g++.exe" }
    default {
        Write-Host "Unsupported file type: $ext"
        exit 1
    }
}

# Set compiler flags based on build type
switch ($buildType.ToLower()) {
    "debug"   { $flags = "-g" }
    "release" { $flags = "-O2" }
    default   { $flags = "-g" } # For anything else safely switched to `debug` mode
}

Write-Host "`n>>> Compiling $filePath as $buildType..."
& $compiler $flags "$filePath" -o "$outputPath"